#include <stdlib.h>
#include <stdio.h>
#include <unistd.h>
#include <time.h>

#define LICZBA_FIRM 744

char* losowanie_firmy(void);

int main(void) {

    char input[100];
    sleep(1.5);
    printf("Witaj\n");
    sleep(1);
    printf("oto w co powinienes dzisiaj zainwestowac!\n");
    sleep(2);
    printf("Wystarczy tylko ze odpowiesz na proste pytanie\n");
    sleep(2);
    printf("Co jadles dzis na sniadanie??: ");
    scanf("%s", input);

    printf("ciekawe");
    sleep(1.5);
    printf(".");
    sleep(1.5);
    printf(".");
    sleep(1.5);
    printf(".\n");
    sleep(1.5);

    printf("Oto dzisiejsza inwestycja!:\n");
    sleep(1.75);

    srand(time(NULL));
    
    char* wylosowane = losowanie_firmy();
    printf("%s\n", wylosowane);

    sleep(1.75);
    return 0;
}


char* losowanie_firmy(void) {

char* firmy[] = {
"3M Company, MMM", 
"ACE Limited, ACE", 
"ADC Telecommunications, ADCT", 
"AES Corporation, AES", 
"AFLAC Inc., AFL", 
"ALLTEL Corp., AT", 
"AT&T Inc., T", 
"Abbott Labs, ABT", 
"Adobe Systems, ADBE", 
"Advanced Micro Devices, AMD", 
"Aetna Inc., AET", 
"Affiliated Computer, ACS", 
"Agilent Technologies, A", 
"Air Products & Chemicals, APD", 
"Alcoa Inc., AA", 
"Allegheny Energy, AYE", 
"Allegheny Technologies Inc, ATI", 
"Allergan, Inc., AGN", 
"Allied Waste Industries, AW", 
"Allstate Corp., ALL", 
"Altera Corp., ALTR", 
"Altria Group, Inc., MO", 
"Amazon Corp., AMZN", 
"Ambac Financial Group, ABK", 
"Ameren Corporation, AEE", 
"American Electric Power, AEP", 
"American Express, AXP", 
"American International Group, AIG", 
"American Standard, ASD", 
"Ameriprise Financial, Inc., AMP", 
"AmerisourceBergen Corp., ABC", 
"Amgen, AMGN", 
"Anadarko Petroleum, APC", 
"Analog Devices, ADI", 
"Anheuser-Busch, BUD", 
"Aon Corp., AOC", 
"Apache Corp., APA", 
"Apartment Investment & Mgmt, AIV", 
"Apollo Group, APOL", 
"Apple Inc., AAPL", 
"Applera Corp-Applied Biosystems Group, ABI", 
"Applied Materials, AMAT", 
"Archer-Daniels-Midland, ADM", 
"Archstone-Smith Trust, ASN", 
"Ashland Inc., ASH", 
"Assurant, AIZ", 
"AutoNation, Inc., AN", 
"AutoZone Inc., AZO", 
"Autodesk, Inc., ADSK", 
"Automatic Data Processing Inc., ADP", 
"AvalonBay Communities, AVB", 
"Avaya Inc., AV", 
"Avery Dennison Corp., AVY", 
"Avon Products, AVP", 
"BB&T Corporation, BBT", 
"BIOGEN IDEC Inc., BIIB", 
"BJ Services, BJS", 
"BMC Software, BMC", 
"Baker Hughes, BHI", 
"Ball Corp., BLL", 
"Bank of America Corp., BAC", 
"Bank of New York, BK", 
"Bard (C.R.) Inc., BCR", 
"Bausch & Lomb, BOL", 
"Baxter International Inc., BAX", 
"Bear Stearns Cos., BSC", 
"Becton, Dickinson, BDX", 
"Bed Bath & Beyond, BBBY", 
"Bemis Company, BMS", 
"Best Buy Co., Inc., BBY", 
"Big Lots, Inc., BIG", 
"Biomet, Inc., BMET", 
"Black & Decker Corp., BDK", 
"Block H&R, HRB", 
"Boeing Company, BA", 
"Boston Properties, BXP", 
"Boston Scientific, BSX", 
"Bristol-Myers Squibb, BMY", 
"Broadcom Corporation, BRCM", 
"Brown-Forman Corp., BF.B", 
"Brunswick Corp., BC", 
"Burlington Northern Santa Fe, BNI", 
"C.H. Robinson Worldwide, CHRW", 
"CA, Inc., CA", 
"CB Richard Ellis Group, CBG", 
"CBS Corp., CBS", 
"CIGNA Corp., CI", 
"CIT Group, CIT", 
"CMS Energy, CMS", 
"CONSOL Energy Inc., CNX", 
"CSX Corp., CSX", 
"CVS/Caremark Corporation, CVS", 
"Campbell Soup, CPB", 
"Capital One Financial, COF", 
"Cardinal Health, Inc., CAH", 
"Carnival Corp., CCL", 
"Caterpillar Inc., CAT", 
"Celgene Corp., CELG", 
"CenterPoint Energy, CNP", 
"Centex Corp., CTX", 
"CenturyTel, CTL", 
"Charles Schwab, SCHW", 
"Chesapeake Energy, CHK", 
"Chevron Corporation, CVX", 
"Chicago Mercantile Exchange, CME", 
"Chubb Corp., CB", 
"Cincinnati Financial, CINF", 
"Cintas Corporation, CTAS", 
"Circuit City Group, CC", 
"Cisco Systems, CSCO", 
"Citigroup Inc., C", 
"Citizens Communications, CZN", 
"Citrix Systems, CTXS", 
"Clear Channel Communications, CCU", 
"Clorox Co., CLX", 
"Coach, Inc., COH", 
"Coca Cola Co., KO", 
"Coca-Cola Enterprises, CCE", 
"Cognizant Technology Solutions, CTSH", 
"Colgate-Palmolive, CL", 
"Comcast Corp., CMCSA", 
"Comerica Inc., CMA", 
"Commerce Bancorp, CBH", 
"Compass Bancshares, CBSS", 
"Computer Sciences Corp., CSC", 
"Compuware Corp., CPWR", 
"ConAgra Foods, Inc., CAG", 
"ConocoPhillips, COP", 
"Consolidated Edison, ED", 
"Constellation Brands, STZ", 
"Constellation Energy Group, CEG", 
"Convergys Corp., CVG", 
"Cooper Industries, Ltd., CBE", 
"Corning Inc., GLW", 
"Costco, COST", 
"Countrywide Financial Corp., CFC", 
"Coventry Health Care Inc., CVH", 
"Cummins Inc., CMI", 
"D.R. Horton, DHI", 
"DIRECTV Group Inc., DTV", 
"DTE Energy Co., DTE", 
"Danaher Corp., DHR", 
"Darden, DRI", 
"Dean Foods, DF", 
"Deere & Co., DE", 
"Dell Inc., DELL", 
"Devon Energy Corp., DVN", 
"Dillard Inc., DDS", 
"Dollar General, DG", 
"Dominion Resources, D", 
"Donnelley (R.R.) & Sons, RRD", 
"Dover Corp., DOV", 
"Dow Chemical, DOW", 
"Dow Jones & Co., DJ", 
"DuPont (E.I.), DD", 
"Duke Energy, DUK", 
"Dynegy Inc., DYN", 
"E*Trade Financial Corp., ETFC", 
"EMC Corporation, EMC", 
"ENSCO International, ESV", 
"EOG Resources, EOG", 
"Eastman Chemical, EMN", 
"Eastman Kodak, EK", 
"Eaton Corp., ETN", 
"eBay Inc., EBAY", 
"Ecolab Inc., ECL", 
"Edison International, EIX", 
"El Paso Corp., EP", 
"Electronic Arts, ERTS", 
"Electronic Data Systems, EDS", 
"Embarq Corporation, EQ", 
"Emerson Electric, EMR", 
"Entergy Corp., ETR", 
"Equifax Inc., EFX", 
"Equity Residential, EQR", 
"Estee Lauder Cos., EL", 
"Exelon Corp., EXC", 
"Express Scripts, ESRX", 
"ExxonMobil Corp., XOM", 
"Fiserv Inc., FISV", 
"FPL Group, FPL", 
"Family Dollar Stores, FDO", 
"Fannie Mae, FNM", 
"FedEx Corporation, FDX", 
"Federal Home Loan Mtg., FRE", 
"Federated Dept. Stores, FD", 
"Federated Investors Inc., FII", 
"Fidelity National Information Services, FIS", 
"Fifth Third Bancorp, FITB", 
"First Data, FDC", 
"First Horizon National, FHN", 
"FirstEnergy Corp., FE", 
"Fluor Corp., FLR", 
"Ford Motor, F", 
"Forest Laboratories, FRX", 
"Fortune Brands, Inc., FO", 
"Franklin Resources, BEN", 
"Freeport-McMoRan Inc., FCX", 
"Gannett Co., GCI", 
"Gap (The), GPS", 
"General Dynamics, GD", 
"General Electric, GE", 
"General Mills, GIS", 
"General Motors, GM", 
"Genuine Parts, GPC", 
"Genworth Financial Inc., GNW", 
"Genzyme Corp., GENZ", 
"Gilead Sciences, GILD", 
"Goldman Sachs Group, GS", 
"Goodrich Corporation, GR", 
"Goodyear Tire & Rubber, GT", 
"Google Inc., GOOG", 
"Grainger (W.W.) Inc., GWW", 
"Halliburton Co., HAL", 
"Harley-Davidson, HOG", 
"Harman International Industries, HAR", 
"Harrahs Entertainment, HET", 
"Hartford Financial Svc.Gp., HIG", 
"Hasbro Inc., HAS", 
"H. J. Heinz Company, HNZ", 
"Hess Corporation, HES", 
"Hewlett-Packard, HPQ", 
"Hilton Hotels, HLT", 
"Home Depot, HD", 
"Honeywell International Inc., HON", 
"Hospira Inc., HSP", 
"Hudson City Bancorp, HCBK", 
"Humana Inc., HUM", 
"Huntington Bancshares, HBAN", 
"IAC/InterActive Corp., IACI", 
"IMS Health Inc., RX", 
"ITT Corporation, ITT", 
"Illinois Tool Works, ITW", 
"Ingersoll-Rand Co. Ltd., IR", 
"Integrys Energy Group, Inc., TEG", 
"Intel Corp., INTC", 
"International Business Machines, IBM", 
"International Flavors & Fragrances, IFF", 
"International Game Technology, IGT", 
"International Paper, IP", 
"Interpublic Group, IPG", 
"Intuit, Inc., INTU", 
"JDS Uniphase Corp., JDSU", 
"JPMorgan Chase & Co., JPM", 
"Jabil Circuit, JBL", 
"Janus Capital Group, JNS", 
"Johnson & Johnson, JNJ", 
"Johnson Controls, JCI", 
"Jones Apparel Group, JNY", 
"Juniper Networks, JNPR", 
"KB Home, KBH", 
"KLA-Tencor Corp., KLAC", 
"Kellogg Co., K", 
"KeyCorp, KEY", 
"Keyspan Energy, KSE", 
"Kimberly-Clark, KMB", 
"Kimco Realty, KIM", 
"Kinder Morgan, KMI", 
"King, KG", 
"Kohls Corp., KSS", 
"Kroger Co., KR", 
"L-3 Communications Holdings, LLL", 
"LSI Logic, LSI", 
"Laboratory Corp. of America Holding, LH", 
"Legg Mason, LM", 
"Leggett & Platt, LEG", 
"Lehman Bros., LEH", 
"Lennar Corp., LEN", 
"Lexmark International Inc., LXK", 
"Eli Lilly and Company, LLY", 
"Limited Brands, Inc., LTD", 
"Lincoln National, LNC", 
"Linear Technology Corp., LLTC", 
"Liz Claiborne, Inc., LIZ", 
"Lockheed Martin Corp., LMT", 
"Loews Corp., LTR", 
"Lowes Cos., LOW", 
"M&T Bank Corp., MTB", 
"MBIA Inc., MBI", 
"MGIC Investment, MTG", 
"Manor Care Inc., HCR", 
"Marathon Oil Corp., MRO", 
"Marriott International, MAR", 
"Marsh & McLennan, MMC", 
"Marshall & Ilsley Corp., MI", 
"Masco Corp., MAS", 
"Mattel, Inc., MAT", 
"Maxim Integrated Products, MXIM", 
"McCormick & Co., MKC", 
"McDonalds Corp., MCD", 
"McGraw-Hill, MHP", 
"McKesson Corporation, MCK", 
"MeadWestvaco Corporation, MWV", 
"Medco Health Solutions Inc., MHS", 
"Medtronic Inc., MDT", 
"Mellon Bank Corp., MEL", 
"Merck & Co., MRK", 
"Meredith Corp., MDP", 
"Merrill Lynch, MER", 
"MetLife Inc., MET", 
"Micron Technology, MU", 
"Microsoft Corp., MSFT", 
"Millipore Corp., MIL", 
"Molex Inc., MOLX", 
"Molson Coors Brewing Company, TAP", 
"Monsanto Co., MON", 
"Monster Worldwide, MNST", 
"Moodys Corp., MCO", 
"Morgan Stanley, MS", 
"Motorola Inc., MOT", 
"Murphy Oil, MUR", 
"Mylan Laboratories, MYL", 
"NCR Corp., NCR", 
"NICOR Inc., GAS", 
"NIKE Inc., NKE", 
"Nvidia, NVDA", 
"Nabors Industries Ltd., NBR", 
"National City Corp., NCC", 
"National Oilwell Varco, Inc., NOV", 
"National Semiconductor, NSM", 
"Network Appliance, NTAP", 
"New York Times, NYT", 
"Newell Rubbermaid Co., NWL", 
"Newmont Mining Corp. (Holding Co.), NEM", 
"News Corporation, NWS.A", 
"NiSource Inc., NI", 
"Noble Corporation, NE", 
"Nordstrom, JWN", 
"Norfolk Southern Corp., NSC", 
"Northern Trust Corp., NTRS", 
"Northrop Grumman Corp., NOC", 
"Novell, Inc., NOVL", 
"Novellus Systems, NVLS", 
"Nucor Corporation, NUE", 
"Occidental Petroleum, OXY", 
"Office Depot, ODP", 
"OfficeMax Inc., OMX", 
"Omnicom Group, OMC", 
"Oracle Corporation, ORCL", 
"PACCAR, PCAR", 
"PG&E Corp., PCG", 
"PMC-Sierra Inc., PMCS", 
"PNC Financial Services, PNC", 
"PPG Industries, PPG", 
"PPL Corp., PPL", 
"Pactiv Corp., PTV", 
"Pall Corp., PLL", 
"Parker-Hannifin, PH", 
"Patterson Companies Inc., PDCO", 
"Paychex Inc., PAYX", 
"Peabody Energy, BTU", 
"J. C. Penney, JCP", 
"Pepsi Bottling Group, PBG", 
"PepsiCo Inc., PEP", 
"PerkinElmer, PKI", 
"Pfizer, PFE", 
"Phelps Dodge, PD", 
"Pinnacle West Capital, PNW", 
"Pitney-Bowes, PBI", 
"Plum Creek Timber Co., PCL", 
"Polo Ralph Lauren Corp., RL", 
"Praxair, Inc., PX", 
"Precision Castparts Corp., PCP", 
"Principal Financial Group, PFG", 
"ProLogis, PLD", 
"Procter & Gamble, PG", 
"Progress Energy, Inc., PGN", 
"Progressive Corp., PGR", 
"Prudential Financial, PRU", 
"Public Service Enterprise Inc., PEG", 
"Public Storage, PSA", 
"Pulte Homes, Inc., PHM", 
"QLogic Corp., QLGC", 
"QUALCOMM Inc., QCOM", 
"Quest Diagnostics, DGX", 
"Questar Corp., STR", 
"Qwest Communications International, Q", 
"RadioShack Corp., RSH", 
"Raytheon Co., RTN", 
"Regions Financial Corporation, RF", 
"Reynolds American Inc., RAI", 
"Robert Half International, RHI", 
"Rockwell Automation, Inc., ROK", 
"Rockwell Collins, COL", 
"Rohm & Haas, ROH", 
"Rowan Companies, RDC", 
"Ryder System, R", 
"SAFECO Corp., SAF", 
"SLM Corporation, SLM", 
"Sabre Holding Corp., TSG", 
"Safeway Inc., SWY", 
"SanDisk Corporation, SNDK", 
"Sanmina-SCI Corp., SANM", 
"Sara Lee Corp., SLE", 
"Schering-Plough, SGP", 
"Schlumberger Ltd., SLB", 
"Scripps (E. W.), SSP", 
"Sealed Air Corp., SEE", 
"Sears Holdings Corporation, SHLD", 
"Sempra Energy, SRE", 
"Sherwin-Williams, SHW", 
"Sigma-Aldrich, SIAL", 
"Simon Property Group, Inc., SPG", 
"Smith International, SII", 
"Snap-On Inc., SNA", 
"Solectron, SLR", 
"Southern Company, SO", 
"Southwest Airlines, LUV", 
"Sovereign Bancorp, SOV", 
"Spectra Energy Corp., SE", 
"Sprint Nextel Corp., S,", 
"St. Jude Medical, STJ", 
"Stanley Works, SWK", 
"Staples Inc., SPLS", 
"Starbucks Corp., SBUX", 
"State Street Corp., STT", 
"Stryker Corp., SYK", 
"Sun Microsystems, SUNW", 
"SunTrust Banks, STI", 
"Sunoco, Inc., SUN", 
"Supervalu Inc., SVU", 
"Symantec Corp., SYMC", 
"Synovus Financial, SNV", 
"Sysco Corporation, SYY", 
"T. Rowe Price Group, TROW", 
"TECO Energy, TE", 
"TJX Companies Inc., TJX", 
"TXU Corp., TXU", 
"Target Corp., TGT", 
"Tektronix, Inc., TEK", 
"Tellabs, Inc., TLAB", 
"Temple-Inland, TIN", 
"Tenet Healthcare Corp., THC", 
"Teradyne Inc., TER", 
"Terex Corp., TEX", 
"Texas Instruments, TXN", 
"Textron Inc., TXT", 
"The Hershey Company, HSY", 
"The Travelers Companies, Inc., TRV", 
"Thermo Fisher Scientific, TMO", 
"Tiffany & Co., TIF", 
"Time Warner Inc., TWX", 
"Torchmark Corp., TMK", 
"Transocean Inc., RIG", 
"Tribune Co., TRB", 
"Tyco International, TYC", 
"Tyson Foods, TSN", 
"U.S. Bancorp, USB", 
"UST Inc., UST", 
"Union Pacific Railroad, UNP", 
"Unisys Corp., UIS", 
"United Health Group Inc., UNH", 
"United Parcel Service, UPS", 
"U.S. Steel, X", 
"United Technologies, UTX", 
"Univision Communications, UVN", 
"Unum, UNM", 
"V.F. Corp., VFC", 
"Valero Energy, VLO", 
"Varian Medical Systems, VAR", 
"VeriSign Inc., VRSN", 
"Verizon Communications, VZ", 
"Viacom Inc., VIA.B", 
"Visa, V", 
"Vornado Realty Trust, VNO", 
"Vulcan Materials, VMC", 
"Wachovia Corp., WB", 
"Wal-Mart Stores, WMT", 
"Walgreen Co., WAG", 
"Walt Disney Co., DIS", 
"Washington Mutual, WM", 
"Waste Management Inc., WMI", 
"Waters Corporation, WAT", 
"Watson Pharmaceuticals, WPI", 
"Weatherford International Ltd., WFT", 
"WellPoint Inc., WLP", 
"Wells Fargo, WFC", 
"Wendys International, WEN", 
"Western Union Co., WU", 
"Weyerhaeuser Corp., WY", 
"Whirlpool Corporation, WHR", 
"Whole Foods Market, WFMI", 
"Williams Companies, WMB", 
"Windstream Corporation, WIN", 
"Wrigley, WWY", 
"Wyeth, WYE", 
"Wyndham Worldwide, WYN", 
"XL Capital, XL", 
"XTO Energy, XTO", 
"Xcel Energy Inc, XEL", 
"Xerox Corp., XRX", 
"International Paper, IP", 
"Interpublic Group, IPG", 
"Intuit, Inc., INTU", 
"JDS Uniphase Corp., JDSU", 
"JPMorgan Chase & Co., JPM", 
"Jabil Circuit, JBL", 
"Janus Capital Group, JNS", 
"Johnson & Johnson, JNJ", 
"Johnson Controls, JCI", 
"Jones Apparel Group, JNY", 
"Juniper Networks, JNPR", 
"KB Home, KBH", 
"KLA-Tencor Corp., KLAC", 
"Kellogg Co., K", 
"KeyCorp, KEY", 
"Keyspan Energy, KSE", 
"Kimberly-Clark, KMB", 
"Kimco Realty, KIM", 
"Kinder Morgan, KMI", 
"King, KG", 
"Kohls Corp., KSS", 
"Kroger Co., KR", 
"L-3 Communications Holdings, LLL", 
"LSI Logic, LSI", 
"Laboratory Corp. of America Holding, LH", 
"Legg Mason, LM", 
"Leggett & Platt, LEG", 
"Lehman Bros., LEH", 
"Lennar Corp., LEN", 
"Lexmark International Inc., LXK", 
"Eli Lilly and Company, LLY", 
"Limited Brands, Inc., LTD", 
"Lincoln National, LNC", 
"Linear Technology Corp., LLTC", 
"Liz Claiborne, Inc., LIZ", 
"Lockheed Martin Corp., LMT", 
"Loews Corp., LTR", 
"Lowe’s Cos., LOW", 
"M&T Bank Corp., MTB", 
"MBIA Inc., MBI", 
"MGIC Investment, MTG", 
"Manor Care Inc., HCR", 
"Marathon Oil Corp., MRO", 
"Marriott International, MAR", 
"Marsh & McLennan, MMC", 
"Marshall & Ilsley Corp., MI", 
"Masco Corp., MAS", 
"Mattel, Inc., MAT", 
"Maxim Integrated Products, MXIM", 
"McCormick & Co., MKC", 
"McDonalds Corp., MCD", 
"McGraw-Hill, MHP", 
"McKesson Corporation, MCK", 
"MeadWestvaco Corporation, MWV", 
"Medco Health Solutions Inc., MHS", 
"Medtronic Inc., MDT", 
"Mellon Bank Corp., MEL", 
"Merck & Co., MRK", 
"Meredith Corp., MDP", 
"Merrill Lynch, MER", 
"MetLife Inc., MET", 
"Micron Technology, MU", 
"Microsoft Corp., MSFT", 
"Millipore Corp., MIL", 
"Molex Inc., MOLX", 
"Molson Coors Brewing Company, TAP", 
"Monsanto Co., MON", 
"Monster Worldwide, MNST", 
"Moodys Corp., MCO", 
"Morgan Stanley, MS", 
"Motorola Inc., MOT", 
"Murphy Oil, MUR", 
"Mylan Laboratories, MYL", 
"NCR Corp., NCR", 
"NICOR Inc., GAS", 
"NIKE Inc., NKE", 
"Nvidia, NVDA", 
"Nabors Industries Ltd., NBR", 
"National City Corp., NCC", 
"National Oilwell Varco, Inc., NOV", 
"National Semiconductor, NSM", 
"Network Appliance, NTAP", 
"New York Times, NYT", 
"Newell Rubbermaid Co., NWL", 
"Newmont Mining Corp. (Holding Co.), NEM", 
"News Corporation, NWS.A", 
"NiSource Inc., NI", 
"Noble Corporation, NE", 
"Nordstrom, JWN", 
"Norfolk Southern Corp., NSC", 
"Northern Trust Corp., NTRS", 
"Northrop Grumman Corp., NOC", 
"Novell, Inc., NOVL", 
"Novellus Systems, NVLS", 
"Nucor Corporation, NUE", 
"Occidental Petroleum, OXY", 
"Office Depot, ODP", 
"OfficeMax Inc., OMX", 
"Omnicom Group, OMC", 
"Oracle Corporation, ORCL", 
"PACCAR, PCAR", 
"PG&E Corp., PCG", 
"PMC-Sierra Inc., PMCS", 
"PNC Financial Services, PNC", 
"PPG Industries, PPG", 
"PPL Corp., PPL", 
"Pactiv Corp., PTV", 
"Pall Corp., PLL", 
"Parker-Hannifin, PH", 
"Patterson Companies Inc., PDCO", 
"Paychex Inc., PAYX", 
"Peabody Energy, BTU", 
"J. C. Penney, JCP", 
"Pepsi Bottling Group, PBG", 
"PepsiCo Inc., PEP", 
"PerkinElmer, PKI", 
"Pfizer, PFE", 
"Phelps Dodge, PD", 
"Pinnacle West Capital, PNW", 
"Pitney-Bowes, PBI", 
"Plum Creek Timber Co., PCL", 
"Polo Ralph Lauren Corp., RL", 
"Praxair, Inc., PX", 
"Precision Castparts Corp., PCP", 
"Principal Financial Group, PFG", 
"ProLogis, PLD", 
"Procter & Gamble, PG", 
"Progress Energy, Inc., PGN", 
"Progressive Corp., PGR", 
"Prudential Financial, PRU", 
"Public Service Enterprise Inc., PEG", 
"Public Storage, PSA", 
"Pulte Homes, Inc., PHM", 
"QLogic Corp., QLGC", 
"QUALCOMM Inc., QCOM", 
"Quest Diagnostics, DGX", 
"Questar Corp., STR", 
"Qwest Communications International, Q", 
"RadioShack Corp., RSH", 
"Raytheon Co., RTN", 
"Regions Financial Corporation, RF", 
"Reynolds American Inc., RAI", 
"Robert Half International, RHI", 
"Rockwell Automation, Inc., ROK", 
"Rockwell Collins, COL", 
"Rohm & Haas, ROH", 
"Rowan Companies, RDC", 
"Ryder System, R", 
"SAFECO Corp., SAF", 
"SLM Corporation, SLM", 
"Sabre Holding Corp., TSG", 
"Safeway Inc., SWY", 
"SanDisk Corporation, SNDK", 
"Sanmina-SCI Corp., SANM", 
"Sara Lee Corp., SLE", 
"Schering-Plough, SGP", 
"Schlumberger Ltd., SLB", 
"Scripps (E. W.), SSP", 
"Sealed Air Corp., SEE", 
"Sears Holdings Corporation, SHLD", 
"Sempra Energy, SRE", 
"Sherwin-Williams, SHW", 
"Sigma-Aldrich, SIAL", 
"Simon Property Group, Inc., SPG", 
"Smith International, SII", 
"Snap-On Inc., SNA", 
"Solectron, SLR", 
"Southern Company, SO", 
"Southwest Airlines, LUV", 
"Sovereign Bancorp, SOV", 
"Spectra Energy Corp., SE", 
"Sprint Nextel Corp., S,", 
"St. Jude Medical, STJ", 
"Stanley Works, SWK", 
"Staples Inc., SPLS", 
"Starbucks Corp., SBUX", 
"State Street Corp., STT", 
"Stryker Corp., SYK", 
"Sun Microsystems, SUNW", 
"SunTrust Banks, STI", 
"Sunoco, Inc., SUN", 
"Supervalu Inc., SVU", 
"Symantec Corp., SYMC", 
"Synovus Financial, SNV", 
"Sysco Corporation, SYY", 
"T. Rowe Price Group, TROW", 
"TECO Energy, TE", 
"TJX Companies Inc., TJX", 
"TXU Corp., TXU", 
"Target Corp., TGT", 
"Tektronix, Inc., TEK", 
"Tellabs, Inc., TLAB", 
"Temple-Inland, TIN", 
"Tenet Healthcare Corp., THC", 
"Teradyne Inc., TER", 
"Terex Corp., TEX", 
"Texas Instruments, TXN", 
"Textron Inc., TXT", 
"The Hershey Company, HSY", 
"Thermo Fisher Scientific, TMO", 
"Tiffany & Co., TIF", 
"Time Warner Inc., TWX", 
"Torchmark Corp., TMK", 
"Transocean Inc., RIG", 
"Tribune Co., TRB", 
"Tyco International, TYC", 
"Tyson Foods, TSN", 
"U.S. Bancorp, USB", 
"UST Inc., UST", 
"Union Pacific Railroad, UNP", 
"Unisys Corp., UIS", 
"United Health Group Inc., UNH", 
"United Parcel Service, UPS", 
"U.S. Steel, X", 
"United Technologies, UTX", 
"Univision Communications, UVN", 
"Unum, UNM", 
"V.F. Corp., VFC", 
"Valero Energy, VLO", 
"Varian Medical Systems, VAR", 
"VeriSign Inc., VRSN", 
"Verizon Communications, VZ", 
"Viacom Inc., VIA.B", 
"Visa, V", 
"Vornado Realty Trust, VNO", 
"Vulcan Materials, VMC", 
"Wachovia Corp., WB", 
"Wal-Mart Stores, WMT", 
"Walgreen Co., WAG", 
"Walt Disney Co., DIS", 
"Washington Mutual, WM", 
"Waste Management Inc., WMI", 
"Waters Corporation, WAT", 
"Watson Pharmaceuticals, WPI", 
"WellPoint Inc., WLP", 
"Wells Fargo, WFC", 
"Wendy’s International, WEN", 
"Western Union Co., WU", 
"Weyerhaeuser Corp., WY", 
"Whirlpool Corporation, WHR", 
"Whole Foods Market, WFMI", 
"Williams Companies, WMB", 
"Windstream Corporation, WIN", 
"Wrigley, WWY", 
"Wyeth, WYE", 
"Wyndham Worldwide, WYN", 
"XL Capital, XL", 
"XTO Energy, XTO", 
"Xcel Energy Inc, XEL", 
"Xerox Corp., XRX", 
"Yum! Brands, Inc., YUM", 
"The Travelers Companies, Inc., TRV", 
"Weatherford International Ltd., WFT", 
"Starwood Hotels and Resorts Worldwide, HOT" };

int random_index = rand() % (sizeof(firmy) / sizeof(firmy[0])); 

return firmy[random_index];

}